### ISSUE TITLE
this mod causes nearly every single lang key in tinkers construct to become untranslated

### ISSUE THREAD

**Issue by NyanMC** [CreepingCreeper/Tinkers-Thinking#1]
just to start off, it was difficult even finding this issue tracker. it isn't linked on the modrinth page in any capacity, nor is any other contact method immediately visible. i had to locate it by going to your github account which is linked to your modrinth account, and finding the issue tracker there.

anyway, this mod replaces tinkers construct's lang files with ones containing singular lines. this did not do what you think it did. that is the equivalent of gutting out every line in the lang file except the one you replaced (and sure enough, that's how it functions in-game).

the proper way of doing this would be changing this line in your mod's lang file, not tinkers' lang file.

![image](https://user-images.githubusercontent.com/44331238/226521737-cd835b23-8bb7-489e-a0de-128a9778ce25.png)
example of missing lang keys, this applies to every item not just this one

![image](https://user-images.githubusercontent.com/44331238/226521774-91650d6b-753d-4b44-8330-a9692c4ce2ca.png)
was it worth it for this singular altered line?

**Comment by CreepingCreeper** [comment]
sorry,I will fixed it as soon as possible
