### ISSUE TITLE
Tinkers' Bronze and Lightite melt down into a single nugget each

### ISSUE THREAD

**Issue by Pixl64** [CreepingCreeper/Tinkers-Thinking#2]
Both metals only melt into a nugget, rather than an ingot
![image](https://user-images.githubusercontent.com/85389249/234346538-2dfbb2cb-7411-4bef-a8e3-7b73dc801d85.png)
![image](https://user-images.githubusercontent.com/85389249/234346599-22d0f6b3-cf2e-492b-817d-56f162745928.png)

**Comment by CreepingCreeper** [comment]
it will be fixed in next verison

**Comment by CreepingCreeper** [comment]
Fixed
